--script do banco
CREATE TABLE PAYMENT (
 PRODUCT_CODE INTEGER NOT NULL,
 PAYMENT_DATE VARCHAR(30) NOT NULL,
 DUE_DATE VARCHAR(30) NOT NULL,
 PAYMENT_TYPE VARCHAR(30) NOT NULL,
 VALUE DOUBLE NOT NULL,
 PRIMARY KEY (PRODUCT_CODE)
);

CREATE TABLE AUDIT (
 ID INTEGER IDENTITY PRIMARY KEY,
 REGISTER_CODE INTEGER NOT NULL,
 OPERATION VARCHAR(30) NOT NULL,
 TIME_STAMP DATE NOT NULL
);