--script do banco
CREATE TABLE PAYMENT (
 PRODUCT_CODE INTEGER NOT NULL,
 PAYMENT_DATE VARCHAR(30) NOT NULL,
 DUE_DATE VARCHAR(30) NOT NULL,
 PAYMENT_TYPE VARCHAR(30) NOT NULL,
 VALUE DOUBLE NOT NULL,
 PRIMARY KEY (PRODUCT_CODE)
);